In [3]:
# In this exercise we'll examine a learner which has high bias, and is incapable of
# learning the patterns in the data.
# Use the learning curve function from sklearn.learning_curve to plot learning curves
# of both training and testing error. Use plt.plot() within the plot_curve function
# to create line graphs of the values.

from sklearn.linear_model import LinearRegression
from sklearn.learning_curve import learning_curve
import matplotlib.pyplot as plt
from sklearn.metrics import explained_variance_score, make_scorer
from sklearn.cross_validation import KFold
import numpy as np

size = 1000
cv = KFold(size,shuffle=True)
score = make_scorer(explained_variance_score)

X = np.reshape(np.random.normal(scale=2,size=size),(-1,1))
y = np.array([[1 - 2*x[0] +x[0]**2] for x in X])

def plot_curve():
    reg = LinearRegression()
    reg.fit(X,y)
    print reg.score(X,y)
    
    # TODO: Create the learning curve with the cv and score parameters defined above.
    [train_size,curve,_]=learning_curve(reg,X,y,cv=cv,scoring=score)
    # TODO: Plot the training and testing curves.
    print train_size
    print curve
    
    
    # Sizes the window for readability and displays the plot.
    plt.ylim(-.1,1.1)
    plt.show()

In [5]:
    reg = LinearRegression()
    reg.fit(X,y)
    print reg.score(X,y)
    
    # TODO: Create the learning curve with the cv and score parameters defined above.
    [train_size,curve,_]=learning_curve(reg,X,y,cv=cv,scoring=score)
    # TODO: Plot the training and testing curves.
    print train_size
    print curve
    
    
    # Sizes the window for readability and displays the plot.
    plt.ylim(-.1,1.1)
    plt.show()

0.328484650459
[ 66 216 366 516 666]
[[ 0.56037294  0.42602044  0.41061331]
 [ 0.29419445  0.3169102   0.25627098]
 [ 0.34285576  0.42669352  0.34271583]
 [ 0.35385713  0.40370958  0.39465071]
 [ 0.32447217  0.34329653  0.31768998]]


In [8]:
curve.mean(axis=1)

array([ 0.4656689 ,  0.28912521,  0.37075504,  0.38407248,  0.32848623])

In [9]:
curve.mean(axis=0)

array([ 0.37515049,  0.38332606,  0.34438816])

In [10]:
train_size

array([ 66, 216, 366, 516, 666])

In [11]:
plt.plot(train_size,curve.mean(axis=1))

In [12]:
plt.show()

In [13]:
# In this exercise we'll examine a learner which has high variance, and tries to learn
# nonexistant patterns in the data.
# Use the learning curve function from sklearn.learning_curve to plot learning curves
# of both training and testing error. Use plt.plot() within the plot_curve function
# to create line graphs of the values.

from sklearn.tree import DecisionTreeRegressor
import matplotlib.pyplot as plt
from sklearn.learning_curve import learning_curve
from sklearn.cross_validation import KFold
from sklearn.metrics import explained_variance_score, make_scorer
import numpy as np

size = 1000
cv = KFold(size,shuffle=True)
score = make_scorer(explained_variance_score)

X = np.round(np.reshape(np.random.normal(scale=5,size=2*size),(-1,2)),2)
y = np.array([[np.sin(x[0]+np.sin(x[1]))] for x in X])

def plot_curve():
    # YOUR CODE HERE
    reg = DecisionTreeRegressor()
    reg.fit(X,y)
    print reg.score(X,y)

    # TODO: Create the learning curve with the cv and score parameters defined above.
    [train_size,curve,_]=learning_curve(reg,X,y,cv=cv,scoring=score)
    # TODO: Plot the training and testing curves.
    plt.plot(train_size,curve.mean(axis=1))
    
    # Show the result, scaling the axis for visibility
    plt.ylim(-.1,1.1)
    plt.show()

In [14]:
    reg = DecisionTreeRegressor()
    reg.fit(X,y)
    print reg.score(X,y)

    # TODO: Create the learning curve with the cv and score parameters defined above.
    [train_size,curve,_]=learning_curve(reg,X,y,cv=cv,scoring=score)
    # TODO: Plot the training and testing curves.
    plt.plot(train_size,curve.mean(axis=1))
    
    # Show the result, scaling the axis for visibility
    plt.ylim(-.1,1.1)
    plt.show()

0.999999998188
